version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install  # Example for a Node.js app
  build:
    commands:
      - echo "Building the application..."
      - npm run build  # Example for a Node.js app
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
  discard-paths: no