version: 0.2

phases:
  install:
    commands:
<<<<<<< HEAD
      - echo "Installing dependencies..."
      - npm install  # Example for a Node.js app
  build:
    commands:
      - echo "Building the application..."
      - npm run build  # Example for a Node.js app
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
  discard-paths: no
=======
      - npm install
  build:
    commands:
      - npm run build  # Builds the project
artifacts:
  files:
    - '**/*'
  base-directory: build  # Directory with output files (e.g., React app)
>>>>>>> 37c5cce3e04da197304a237b570a509db1d86e87
