version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run dev 
      post_build:
      commands:
      - aws s3 cp --recursive ./build s3://auth-registration-bucket
      - aws cloudfront create-invalidation --distribution-id E388W75PDVC0ZE --path /\*
artifacts:
  files:
    - '**/*'
  base-directory: build  # Directory with output files (e.g., React app)